/**
 * Default leave-type catalogue, seeded per company from the Iranian labour-law
 * leave directive (EKWI-AD-006-01). Every field is editable per company from
 * the admin panel — each organisation may tune its own rules.
 */

export interface LeaveTypeSeed {
  code: string;
  name: string;
  unit: "day" | "hour";
  paid: boolean;
  /** Deducted from the annual entitlement balance (استحقاقی). */
  deducts_entitlement: boolean;
  /** Do official holidays / Fridays inside the range count as leave? (تبصره۱) */
  counts_inner_holidays: boolean;
  /** Requires a supporting document (medical certificate, etc.). */
  requires_attachment: boolean;
  max_minutes_per_day: number | null; // hourly ceiling per day
  max_count_per_month: number | null; // max occurrences per month
  max_count_per_week: number | null; // max occurrences per week
  max_days_per_year: number | null; // annual cap in days
  approval_levels: number; // approval chain length
  sort_order: number;
  description: string;
}

export const DEFAULT_LEAVE_TYPES: LeaveTypeSeed[] = [
  {
    code: "entitlement_daily",
    name: "مرخصی استحقاقی روزانه",
    unit: "day",
    paid: true,
    deducts_entitlement: true,
    counts_inner_holidays: false,
    requires_attachment: false,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: 30,
    approval_levels: 2,
    sort_order: 10,
    description: "۲.۵ روز در ماه، سالانه ۳۰ روز با احتساب ۴ جمعه (ماده ۶۴ و ۶۷ قانون کار).",
  },
  {
    code: "entitlement_hourly",
    name: "مرخصی ساعتی",
    unit: "hour",
    paid: true,
    deducts_entitlement: true,
    counts_inner_holidays: false,
    requires_attachment: false,
    max_minutes_per_day: 240,
    max_count_per_month: 5,
    max_count_per_week: null,
    max_days_per_year: null,
    approval_levels: 2,
    sort_order: 20,
    description: "حداکثر ۴ ساعت در روز و ۵ نوبت در ماه؛ بیش از ۴ ساعت به مرخصی روزانه تبدیل می‌شود.",
  },
  {
    code: "sick",
    name: "مرخصی استعلاجی",
    unit: "day",
    paid: false,
    deducts_entitlement: false,
    counts_inner_holidays: false,
    requires_attachment: true,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: null,
    approval_levels: 2,
    sort_order: 30,
    description: "با گواهی پزشک و تأیید تأمین اجتماعی؛ حقوق از طرف شرکت پرداخت نمی‌شود (ماده ۷۴).",
  },
  {
    code: "unpaid",
    name: "مرخصی بدون حقوق",
    unit: "day",
    paid: false,
    deducts_entitlement: false,
    counts_inner_holidays: true,
    requires_attachment: false,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: 30,
    approval_levels: 2,
    sort_order: 40,
    description: "حداکثر ۱ ماه در سال؛ تا ۷ روز تأیید سرپرست و کمیته، بیش از آن مدیرعامل (ماده ۷۲).",
  },
  {
    code: "lactation",
    name: "مرخصی شیردهی",
    unit: "hour",
    paid: true,
    deducts_entitlement: false,
    counts_inner_holidays: false,
    requires_attachment: false,
    max_minutes_per_day: 90,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: null,
    approval_levels: 2,
    sort_order: 50,
    description: "تا ۲ سالگی کودک؛ جزو ساعات کار و بدون کسر از استحقاقی (ماده ۷۸). دوقلو ۲ ساعت.",
  },
  {
    code: "maternity",
    name: "مرخصی زایمان",
    unit: "day",
    paid: false,
    deducts_entitlement: false,
    counts_inner_holidays: true,
    requires_attachment: true,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: 270,
    approval_levels: 2,
    sort_order: 60,
    description: "۹ ماه؛ پرداخت توسط سازمان تأمین اجتماعی (ماده ۷۶).",
  },
  {
    code: "marriage_bereavement",
    name: "مرخصی ازدواج و فوت",
    unit: "day",
    paid: true,
    deducts_entitlement: false,
    counts_inner_holidays: true,
    requires_attachment: true,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: 3,
    approval_levels: 2,
    sort_order: 70,
    description: "۳ روز برای ازدواج دائم یا فوت بستگان درجه یک؛ بدون کسر از استحقاقی (ماده ۷۳).",
  },
  {
    code: "incentive",
    name: "مرخصی تشویقی",
    unit: "day",
    paid: true,
    deducts_entitlement: false,
    counts_inner_holidays: false,
    requires_attachment: false,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: null,
    approval_levels: 2,
    sort_order: 80,
    description: "با درخواست مدیر واحد و موافقت مدیرعامل برای تشویق کارکنان کوشا.",
  },
  {
    code: "hajj",
    name: "مرخصی حج",
    unit: "day",
    paid: true,
    deducts_entitlement: true,
    counts_inner_holidays: false,
    requires_attachment: true,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: 30,
    approval_levels: 2,
    sort_order: 90,
    description: "یک ماه برای حج تمتع واجب؛ از محل ۳۰ روز استحقاقی (ماده ۶۷).",
  },
  {
    code: "study",
    name: "مرخصی تحصیلی",
    unit: "day",
    paid: false,
    deducts_entitlement: false,
    counts_inner_holidays: true,
    requires_attachment: false,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: null,
    approval_levels: 2,
    sort_order: 100,
    description: "بدون حقوق با مجوز مدیرعامل؛ قابل تهاتر با اضافه‌کار.",
  },
  {
    code: "exit_permit",
    name: "مجوز خروج",
    unit: "hour",
    paid: true,
    deducts_entitlement: false,
    counts_inner_holidays: false,
    requires_attachment: false,
    max_minutes_per_day: 10,
    max_count_per_month: null,
    max_count_per_week: 2,
    max_days_per_year: null,
    approval_levels: 2,
    sort_order: 110,
    description: "حداکثر ۱۰ دقیقه و دو بار در هفته در زمان موظفی.",
  },
  {
    code: "mission",
    name: "مأموریت",
    unit: "day",
    paid: true,
    deducts_entitlement: false,
    counts_inner_holidays: true,
    requires_attachment: false,
    max_minutes_per_day: null,
    max_count_per_month: null,
    max_count_per_week: null,
    max_days_per_year: null,
    approval_levels: 2,
    sort_order: 120,
    description: "مأموریت کاری خارج از محل؛ بدون کسر از مرخصی.",
  },
];
